### ISSUE TITLE
Cannot resolve ambiguous delegation of public io.restassured.specification.ResponseSpecification

### ISSUE THREAD

**Issue by stalexmr** [viclovsky/swagger-coverage#25]
Hello.

Just after added lib to gradle dependencies:

`compile "com.github.viclovsky.swagger.coverage:swagger-coverage-rest-assured:1.1.1"`

I had countered with error after launch any API test:

`Cannot resolve ambiguous delegation of public io.restassured.specification.ResponseSpecification io.restassured.specification.ResponseSpecification.root(java.lang.String) to net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@dde054d7 or net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@a260d9b7
`
I can provide any information for localization this issue.

**Comment by stalexmr** [comment]
Additional info:

`java.lang.ExceptionInInitializerError
net.serenitybdd.rest.utils.RestDecorationHelper.decorate(RestDecorationHelper.java:20)
net.serenitybdd.rest.SerenityRest.given(SerenityRest.java:215)
com.tsum.steps.api.AddCommentSteps.getAddClientComment(AddCommentSteps.java:23)
com.tsum.tests.api.AddClientComment.successAddClientCommentToExistentOrder(AddClientComment.java:30)
Caused by: java.lang.IllegalArgumentException
Cannot resolve ambiguous delegation of public io.restassured.specification.ResponseSpecification io.restassured.specification.ResponseSpecification.root(java.lang.String) to net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@dde054d7 or net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build@a260d9b7
net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java :225)
net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java :198)
net.serenitybdd.rest.utils.RestSpecificationFactory.(RestSpecificationFactory.java :53)
net.serenitybdd.rest.utils.RestDecorationHelper.decorate(RestDecorationHelper.java :20)
net.serenitybdd.rest.SerenityRest.given(SerenityRest.java :215))`

**Comment by viclovsky** [comment]
Hi, @stalexmr 
To be honest I need more information to reproduce your issue. It would be great if you add some example right to GitHub. Thanks.

**Comment by mohitb01** [comment]
Hi,
I am also getting the same issue. Can anyone please help.
Below is my dependency tree.

[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.5.4:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:2.5.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.5.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.5.4:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.5:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.2.5:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.14.1:compile
[INFO] |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.14.1:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.32:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  +- org.springframework:spring-core:jar:5.3.9:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.9:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.28:compile
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.5.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.5.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.4:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.4:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.4:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.12.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.5.4:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.52:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.52:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.52:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.9:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.9:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.9:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.3.9:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.9:compile
[INFO] +- net.serenity-bdd:serenity-spring:jar:2.6.0:test
[INFO] |  +- junit:junit:jar:4.13.2:compile
[INFO] |  +- org.springframework:spring-context:jar:5.3.9:compile
[INFO] |  \- org.springframework:spring-context-support:jar:5.3.9:test
[INFO] +- net.serenity-bdd:serenity-core:jar:1.9.45:compile
[INFO] |  +- com.google.guava:guava:jar:25.0-jre:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  |  +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |  +- com.google.inject:guice:jar:4.2.0:compile
[INFO] |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- cglib:cglib:jar:3.2.5:compile
[INFO] |  |  \- org.apache.ant:ant:jar:1.9.6:compile
[INFO] |  |     \- org.apache.ant:ant-launcher:jar:1.9.6:compile
[INFO] |  +- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- org.objenesis:objenesis:jar:2.6:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.32:compile
[INFO] |  +- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  +- io.cucumber:cucumber-core:jar:2.4.0:compile
[INFO] |  |  +- info.cukes:cucumber-html:jar:0.2.6:compile
[INFO] |  |  +- io.cucumber:cucumber-jvm-deps:jar:1.0.6:compile
[INFO] |  |  +- io.cucumber:gherkin:jar:5.0.0:compile
[INFO] |  |  \- io.cucumber:tag-expressions:jar:1.1.1:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  +- org.mockito:mockito-core:jar:3.9.0:compile
[INFO] |  |  \- net.bytebuddy:byte-buddy-agent:jar:1.10.22:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.10.22:compile
[INFO] |  +- io.vavr:vavr:jar:0.9.0:compile
[INFO] |  |  \- io.vavr:vavr-match:jar:0.9.0:compile
[INFO] |  +- net.serenity-bdd:serenity-report-resources:jar:1.9.45:compile
[INFO] |  +- net.serenity-bdd:serenity-model:jar:1.9.45:compile
[INFO] |  |  \- commons-net:commons-net:jar:3.6:compile
[INFO] |  +- net.serenity-bdd:serenity-reports:jar:1.9.45:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.7:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-server:jar:3.14.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.141.59:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.141.59:compile
[INFO] |  |  +- com.beust:jcommander:jar:1.72:compile
[INFO] |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  +- org.apache.commons:commons-text:jar:1.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.14:compile
[INFO] |  |  +- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:jetty-repacked:jar:9.4.8.v20180619:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-client:jar:9.4.43.v20210629:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.43.v20210629:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-xml:jar:9.4.43.v20210629:compile
[INFO] |  |  +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |  +- com.squareup.okio:okio:jar:1.14.1:compile
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-api:jar:9.4.43.v20210629:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-client:jar:9.4.43.v20210629:compile
[INFO] |  |  +- org.eclipse.jetty.websocket:websocket-common:jar:9.4.43.v20210629:compile
[INFO] |  |  \- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.141.59:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-support:jar:3.141.59:compile
[INFO] |  +- com.paulhammant:ngwebdriver:jar:1.1.4:compile
[INFO] |  +- com.codeborne:phantomjsdriver:jar:1.4.4:compile
[INFO] |  +- org.eclipse.jetty:jetty-util:jar:9.4.43.v20210629:compile
[INFO] |  +- org.eclipse.jetty:jetty-io:jar:9.4.43.v20210629:compile
[INFO] |  +- org.seleniumhq.selenium:htmlunit-driver:jar:2.49.1:compile
[INFO] |  +- io.appium:java-client:jar:6.1.0:compile
[INFO] |  |  +- org.aspectj:aspectjweaver:jar:1.9.7:compile
[INFO] |  |  \- org.openpnp:opencv:jar:3.2.0-1:compile
[INFO] |  +- org.glassfish.tyrus:tyrus-core:jar:1.13.1:compile
[INFO] |  |  \- org.glassfish.tyrus:tyrus-spi:jar:1.13.1:compile
[INFO] |  |     \- javax.websocket:javax.websocket-api:jar:1.1:compile
[INFO] |  +- org.codehaus.groovy:groovy:jar:3.0.8:compile
[INFO] |  +- net.sf.opencsv:opencsv:jar:2.0:compile
[INFO] |  +- commons-beanutils:commons-beanutils-core:jar:1.8.3:compile
[INFO] |  +- joda-time:joda-time:jar:2.7:compile
[INFO] |  +- com.thoughtworks.xstream:xstream:jar:1.4.9:compile
[INFO] |  |  +- xmlpull:xmlpull:jar:1.1.3.1:compile
[INFO] |  |  \- xpp3:xpp3_min:jar:1.1.4c:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] |  +- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  +- org.freemarker:freemarker:jar:2.3.31:compile
[INFO] |  +- net.sourceforge.jexcelapi:jxl:jar:2.6.12:compile
[INFO] |  +- org.hamcrest:hamcrest-core:jar:2.2:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:2.2:compile
[INFO] |  +- net.sourceforge.htmlunit:htmlunit:jar:2.49.1:compile
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.49.0:compile
[INFO] |  |  +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.49.0:compile
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit-cssparser:jar:1.7.0:compile
[INFO] |  |  +- org.brotli:dec:jar:0.1.2:compile
[INFO] |  |  \- com.shapesecurity:salvation2:jar:3.0.0:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.13:compile
[INFO] |  +- org.fluentlenium:fluentlenium-core:jar:0.10.2:compile
[INFO] |  +- com.jhlabs:filters:jar:2.0.235:compile
[INFO] |  +- org.asciidoctor:asciidoctorj:jar:1.5.6:compile
[INFO] |  |  \- org.jruby:jruby-complete:jar:1.7.26:runtime
[INFO] |  +- org.imgscalr:imgscalr-lib:jar:4.2:compile
[INFO] |  +- javax.el:javax.el-api:jar:2.2.4:compile
[INFO] |  +- org.glassfish.web:javax.el:jar:2.2.4:compile
[INFO] |  +- xalan:xalan:jar:2.7.2:compile
[INFO] |  +- xalan:serializer:jar:2.7.2:compile
[INFO] |  +- org.awaitility:awaitility:jar:4.0.3:compile
[INFO] |  +- com.typesafe:config:jar:1.3.1:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.10.3:compile
[INFO] |  +- com.google.jimfs:jimfs:jar:1.1:compile
[INFO] |  +- es.nitaur.markdown:txtmark:jar:0.16:compile
[INFO] |  \- com.vladsch.flexmark:flexmark-all:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-abbreviation:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-anchorlink:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-aside:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-autolink:jar:0.26.4:compile
[INFO] |     |  \- org.nibor.autolink:autolink:jar:0.6.0:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-definition:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-emoji:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-escaped-character:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-footnotes:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-issues:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-strikethrough:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-tables:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-tasklist:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-gfm-users:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-jekyll-front-matter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-jekyll-tag:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-ins:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-xwiki-macros:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-superscript:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-tables:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-toc:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-typographic:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-wikilink:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-ext-yaml-front-matter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-formatter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-html-parser:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-jira-converter:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-pdf-converter:jar:0.26.4:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-core:jar:0.0.1-RC9:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-pdfbox:jar:0.0.1-RC9:compile
[INFO] |     |  |  \- org.apache.pdfbox:pdfbox:jar:2.0.4:compile
[INFO] |     |  |     \- org.apache.pdfbox:fontbox:jar:2.0.4:compile
[INFO] |     |  +- com.openhtmltopdf:openhtmltopdf-rtl-support:jar:0.0.1-RC9:compile
[INFO] |     |  |  \- com.ibm.icu:icu4j:jar:58.1:compile
[INFO] |     |  \- com.openhtmltopdf:openhtmltopdf-jsoup-dom-converter:jar:0.0.1-RC9:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-profile-pegdown:jar:0.26.4:compile
[INFO] |     +- com.vladsch.flexmark:flexmark-util:jar:0.26.4:compile
[INFO] |     \- com.vladsch.flexmark:flexmark-youtrack-converter:jar:0.26.4:compile
[INFO] +- net.serenity-bdd:serenity-rest-assured:jar:1.9.45:compile
[INFO] |  +- io.rest-assured:rest-assured:jar:4.3.3:compile
[INFO] |  |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:compile
[INFO] |  |  +- io.rest-assured:json-path:jar:4.3.3:compile
[INFO] |  |  |  \- io.rest-assured:rest-assured-common:jar:4.3.3:compile
[INFO] |  |  \- io.rest-assured:xml-path:jar:4.3.3:compile
[INFO] |  +- org.codehaus.groovy:groovy-xml:jar:3.0.8:compile
[INFO] |  \- org.codehaus.groovy:groovy-json:jar:3.0.8:compile
[INFO] +- net.serenity-bdd:serenity-junit:jar:1.9.45:compile
[INFO] +- net.serenity-bdd:serenity-cucumber:jar:1.9.31:compile
[INFO] |  +- net.serenity-bdd:serenity-screenplay:jar:2.0.40:compile
[INFO] |  |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  |  +- com.sun.xml.bind:jaxb-core:jar:2.3.0.1:compile
[INFO] |  |  +- com.sun.xml.bind:jaxb-impl:jar:2.3.0.1:compile
[INFO] |  |  +- javax.activation:activation:jar:1.1.1:compile
[INFO] |  |  \- uk.com.robust-it:cloning:jar:1.9.10:compile
[INFO] |  +- net.serenity-bdd:serenity-screenplay-webdriver:jar:2.0.40:compile
[INFO] |  +- io.cucumber:cucumber-java:jar:2.4.0:compile
[INFO] |  +- io.cucumber:cucumber-junit:jar:2.4.0:compile
[INFO] |  \- org.apache.commons:commons-csv:jar:1.5:compile
[INFO] +- io.rest-assured:json-schema-validator:jar:3.0.0:compile
[INFO] |  \- com.github.fge:json-schema-validator:jar:2.2.6:compile
[INFO] |     +- com.googlecode.libphonenumber:libphonenumber:jar:6.2:compile
[INFO] |     +- com.github.fge:json-schema-core:jar:1.2.5:compile
[INFO] |     |  +- com.github.fge:uri-template:jar:0.9:compile
[INFO] |     |  |  \- com.github.fge:msg-simple:jar:1.1:compile
[INFO] |     |  |     \- com.github.fge:btf:jar:1.2:compile
[INFO] |     |  +- com.github.fge:jackson-coreutils:jar:1.8:compile
[INFO] |     |  \- org.mozilla:rhino:jar:1.7R4:compile
[INFO] |     +- javax.mail:mailapi:jar:1.4.3:compile
[INFO] |     \- net.sf.jopt-simple:jopt-simple:jar:4.6:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.20:compile (optional) 
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.5.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.5.4:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.5.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.7:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.7:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.19.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:compile
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.2:test
[INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.9.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.8.2:test
[INFO] +- org.springframework.boot:spring-boot-test:jar:2.5.4:compile
[INFO] +- org.springframework:spring-test:jar:5.3.9:compile
[INFO] \- org.everit.json:org.everit.json.schema:jar:1.5.1:compile
[INFO]    +- org.json:json:jar:20160810:compile
[INFO]    \- commons-validator:commons-validator:jar:1.5.1:compile
[INFO]       +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO]       \- commons-digester:commons-digester:jar:1.8.1:compile

**Comment by mohitb01** [comment]
Exception : 

java.lang.ExceptionInInitializerError
	at net.serenitybdd.rest.utils.RestDecorationHelper.decorate(RestDecorationHelper.java:20)
	at net.serenitybdd.rest.SerenityRest.given(SerenityRest.java:220)
	at com.imqa.api.automation.services.SerenityServices.post(SerenityServices.java:20)
	at com.imqa.api.automation.stepDefinition.PetStepDef.userSendThePostRequestWithValidJsonBodyWithContentType(PetStepDef.java:55)
	at ✽.User send the Post request with valid json body "pet" with content type "JSON"(src/test/resources/features/pet.feature:8)
**Caused by: java.lang.IllegalArgumentException: Cannot resolve ambiguous delegation of public** io.restassured.specification.ResponseSpecification io.restassured.specification.ResponseSpecification.appendRoot(java.lang.String) to public io.restassured.specification.ResponseSpecification io.restassured.internal.ResponseSpecificationImpl.appendRootPath(java.lang.String) or public io.restassured.specification.ResponseSpecification io.restassured.internal.ResponseSpecificationImpl.detachRootPath(java.lang.String)
	at net
