### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by SergeyPirogov** [viclovsky/swagger-coverage#43]
Tried to run and got NPE:
Version 1.4.0. 
CMD version 2.0

```
 ./swagger-coverage-commandline -s api-docs.json -i swagger-coverage-output/cabed636-149c-4e5c-9bcb-e7c10bc3994d-coverage.json 
```
Sample data:

[data.zip](https://github.com/viclovsky/swagger-coverage/files/4414892/data.zip)

Error message:

```
bin ./swagger-coverage-commandline -s api-docs.json -i swagger-coverage-output/cabed636-149c-4e5c-9bcb-e7c10bc3994d-coverage.json            
[main] INFO io.swagger.parser.Swagger20Parser - reading from api-docs.json
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'One': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"{"swagger":"2.0","info":{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":{},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"}},"host":"localhost:8080","basePath":"/","tags":[{"name":"episode-controller","description":"Episode Controller"},{"name":"post-controller","description":"Post Controller"},{"name":"sse-controller","description":"Sse Controller"},{"name":"theme-controller","description":"The"[truncated 13033 chars]; line: 1, column: 12330]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:722)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2868)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1914)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:261)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4254)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:209)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:122)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:79)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:58)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Generator.java:36)
        at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.java:93)
        at java.util.Optional.orElseGet(Optional.java:267)
        at com.github.viclovsky.swagger.coverage.CommandLine.main(CommandLine.java:50)
[main] INFO io.swagger.parser.Swagger20Parser - reading from api-docs.json
Exception in thread "main" java.lang.NullPointerException
        at com.github.viclovsky.swagger.coverage.core.generator.SwaggerSpecificationProcessor.extractOperation(SwaggerSpecificationProcessor.java:20)
        at com.github.viclovsky.swagger.coverage.core.generator.OperationConditionGenerator.getOperationMap(OperationConditionGenerator.java:25)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Generator.java:40)
        at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.java:93)
        at java.util.Optional.orElseGet(Optional.java:267)
```

**Comment by SergeyPirogov** [comment]
Bug in swagger.json
