### ISSUE TITLE
Comandline run with -c parameter throw java.lang.NullPointerException

### ISSUE THREAD

**Issue by scripnichenko** [viclovsky/swagger-coverage#56]
:green_book:  Works well: 
_swagger-coverage-commandline -s buddle_swagger.json -i swagger-coverage-output_ 

:red_square: Throw `java.lang.NullPointerException`
_swagger-coverage-commandline -s buddle_swagger.json -i swagger-coverage-output -c config.json_

Where **config.json**
```
{
  "writers": {
      "html": {
        "locale": "en",
        "filename":"buddle_swagger_cov_report.html"
      }
  }
}

```

:information_source: Stacktrace: 

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from buddle_swagger.json

[main] INFO com.github.viclovsky.swagger.coverage.core.generator.Generator - spe
c is io.swagger.models.Swagger@119cd9a6
Exception in thread "main" java.lang.NullPointerException
        at com.github.viclovsky.swagger.coverage.configuration.ConfigurationBuil
der.lambda$getResultsWriters$0(ConfigurationBuilder.java:67)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.github.viclovsky.swagger.coverage.configuration.ConfigurationBuil
der.getResultsWriters(ConfigurationBuilder.java:66)
        at com.github.viclovsky.swagger.coverage.configuration.ConfigurationBuil
der.build(ConfigurationBuilder.java:52)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Ge
nerator.java:36)
        at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.jav
a:74)
        at java.util.Optional.orElseGet(Optional.java:267)
        at com.github.viclovsky.swagger.coverage.CommandLine.main(CommandLine.ja
va:35)
```

**Comment by viclovsky** [comment]
Hi, @scripnichenko . There is a bug in documentation. Please, try this  
```
{
  "writers": {
      "html": {
        "type": "html",
        "locale": "en",
        "filename":"buddle_swagger_cov_report.html"
      }
  }
}

```
It should help.
