### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException with 3 parameters

### ISSUE THREAD

**Issue by akvinich** [viclovsky/swagger-coverage#59]
C:\swagger-coverage-commandline-1.3.0\bin>swagger-coverage-commandline -s swagger.json -i swagger-coverage-output -c config.json
swagger.json
{
  "rules" : {
    "status": {
      "enable": true,
      "ignore": ["400","500"],
      "filter": ["200"]
    },
	"only-declareted-status" : {
      "enable" : true
    }
  }
}
config.json
{
  "writers": {
      "html": {
        "type": "html",
        "locale": "en",
        "filename":"buddle_swagger_cov_report.html"
      }
  }
}
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger.json
[main] INFO com.github.viclovsky.swagger.coverage.core.generator.Generator - spec is null
Exception in thread "main" java.lang.NullPointerException
        at com.github.viclovsky.swagger.coverage.core.generator.SwaggerSpecificationProcessor.extractOperation(SwaggerSpecificationProcessor.java:21)
        at com.github.viclovsky.swagger.coverage.core.generator.OperationConditionGenerator.getOperationMap(OperationConditionGenerator.java:24)
        at com.github.viclovsky.swagger.coverage.core.results.builder.prebuilder.CoverageStatisticsBuilder.configure(CoverageStatisticsBuilder.java:36)
        at com.github.viclovsky.swagger.coverage.core.results.builder.prebuilder.CoverageStatisticsBuilder.configure(CoverageStatisticsBuilder.java:28)
        at com.github.viclovsky.swagger.coverage.configuration.Configuration.lambda$getStatisticsBuilders$2(Configuration.java:44)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.github.viclovsky.swagger.coverage.configuration.Configuration.getStatisticsBuilders(Configuration.java:46)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Generator.java:37)
        at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.java:74)
        at java.base/java.util.Optional.orElseGet(Optional.java:362)
        at com.github.viclovsky.swagger.coverage.CommandLine.main(CommandLine.java:35)

**Comment by viclovsky** [comment]
I have looked at it. I write tests with similar configuration and haven't got a error.

`INFO com.github.viclovsky.swagger.coverage.core.generator.Generator - spec is null`
Please, check path to you specification.
