### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException in "TagStatisticsBuilder"

### ISSUE THREAD

**Issue by savvagen** [viclovsky/swagger-coverage#60]
Got an exception while comparing 2 json files for swaggger 2.0:

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from swagger/swagger-v2.json
[main] INFO com.github.viclovsky.swagger.coverage.core.generator.Generator - spec is io.swagger.models.Swagger@890d20db
Exception in thread "main" java.lang.NullPointerException
	at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.lambda$null$1(TagStatisticsBuilder.java:43)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.lambda$configure$2(TagStatisticsBuilder.java:43)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.configure(TagStatisticsBuilder.java:43)
	at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.configure(TagStatisticsBuilder.java:22)
	at com.github.viclovsky.swagger.coverage.configuration.Configuration.lambda$getStatisticsBuilders$2(Configuration.java:44)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.viclovsky.swagger.coverage.configuration.Configuration.getStatisticsBuilders(Configuration.java:46)
	at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Generator.java:37)
	at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.java:74)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at com.github.viclovsky.swagger.coverage.CommandLine.main(CommandLine.java:35)

FAILURE: Build failed with an exception.

```

I think the broblem is somewhere here:
`com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.lambda$null$1(TagStatisticsBuilder.java:43)`

My Gradle configurations:

```
ext {
   swaggerCoverageVersion = "1.3.1"
}

compile {
      compile group: 'com.github.viclovsky.swagger.coverage', name: 'swagger-coverage-rest-assured', version: "${swaggerCoverageVersion}"

}

task downloadSwaggerCoverage(type: Download){
    src " https://dl.bintray.com/viclovsky/maven/com/github/viclovsky/swagger/coverage/swagger-coverage-commandline/${swaggerCoverageVersion}/swagger-coverage-commandline-${swaggerCoverageVersion}.zip"
    dest "swagger-coverage-${swaggerCoverageVersion}.zip"
    doLast {
        exec {
            commandLine 'sh', '-c', "unzip swagger-coverage-${swaggerCoverageVersion}.zip -x &&" +
                    "mv swagger-coverage-commandline-$swaggerCoverageVersion swagger-coverage-$swaggerCoverageVersion &&" +
                    "./swagger-coverage-$swaggerCoverageVersion/bin/swagger-coverage-commandline -s $swaggerV2 -i swagger-coverage-output"
        }
    }
}

```

Swagger coverage output file:

```
{
  "swagger": "2.0",
  "host": "localhost",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json; charset=UTF-8"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/get_token/": {
      "get": {
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": false,
            "x-example": "application/json"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": false,
            "x-example": "application/json; charset=UTF-8"
          }
        ],
        "responses": {
          "200": {
            
          }
        }
      }
    }
  }
}

```

**Comment by savvagen** [comment]
Works fine only with swagger coverage version: 1.2.0
