### ISSUE TITLE
Error on swagger parser 

### ISSUE THREAD

**Issue by SergeyVinickiy** [viclovsky/swagger-coverage#65]
Hi Victor,
Thanks for sharing this project

Getting this error on one of the swaggers, for another it works fine 

[main] INFO io.swagger.parser.Swagger20Parser - reading from appmarketqa.json
[main] INFO com.github.viclovsky.swagger.coverage.core.generator.Generator - spec is io.swagger.models.Swagger@13eef5a4
[main] INFO com.github.viclovsky.swagger.coverage.configuration.ConfigurationBuilder - can't read configuration, use default configuration
Exception in thread "main" java.lang.NullPointerException
        at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.lambda$null$1(TagStatisticsBuilder.java:43)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.lambda$configure$2(TagStatisticsBuilder.java:43)
        at java.util.HashMap.forEach(Unknown Source)
        at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.configure(TagStatisticsBuilder.java:43)
        at com.github.viclovsky.swagger.coverage.core.results.builder.postbuilder.TagStatisticsBuilder.configure(TagStatisticsBuilder.java:22)
        at com.github.viclovsky.swagger.coverage.configuration.Configuration.lambda$getStatisticsBuilders$2(Configuration.java:44)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at com.github.viclovsky.swagger.coverage.configuration.Configuration.getStatisticsBuilders(Configuration.java:46)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Generator.java:37)
        at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.java:74)
        at java.util.Optional.orElseGet(Unknown Source)
        at com.github.viclovsky.swagger.coverage.CommandLine.main(CommandLine.java:35)

**Comment by SergeyVinickiy** [comment]
We found missing tag in swagger. Not a bug
Great project,
Thanks a lot!

**Comment by viclovsky** [comment]
Hello, @SergeyVinickiy 

Could you give swagger-coverage version? Sounds like we already fixed something similar here:  https://github.com/viclovsky/swagger-coverage/issues/60
Anyway, to understand a root cause I need an example with specification and swagger-coverage-output .

**Comment by SergeyVinickiy** [comment]
I have swagger-coverage-commandline-1.3.1
Please writhe me on mail - svinickiy@gmail.com if some other data you need

**Comment by viclovsky** [comment]
@SergeyVinickiy could you check the latest version of swagger-coverage, I have merged some fixes.
