### ISSUE TITLE
Exception with openapi.json without parameters

### ISSUE THREAD

**Issue by Morena51** [viclovsky/swagger-coverage#87]
I try to build swagger-coverage with command line option -s <openapi.json> -i <openapi.json>
In my swagger-api spec I dont have "parameters" section.
Unfortunately it is failed with error

```
----
FTL stack trace ("~" means nesting-related):
        - Failed at: #list value.getParameters() as p  [in template "details/operation.ftl" in macro "list" at line 39, column 41]
        - Reached through: @operations.list coverage=data.deprec...  [in template "report.ftl" at line 166, column 29]
----
Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
        at freemarker.core.Expression.assertNonNull(Expression.java:251)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:104)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:367)
        at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForHashListing(IteratorBlock.java:383)
        at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:272)
        at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
        at freemarker.core.Environment.visitIteratorBlock(Environment.java:643)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
        at freemarker.core.Environment.visit(Environment.java:367)
        at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:872)
        at freemarker.core.Environment.invokeMacro(Environment.java:809)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:83)
        at freemarker.core.Environment.visit(Environment.java:331)
        at freemarker.core.Environment.visit(Environment.java:337)
        at freemarker.core.Environment.process(Environment.java:310)
        at freemarker.template.Template.process(Template.java:383)
        at com.github.viclovsky.swagger.coverage.utils.FreemarkerUtils.proccessTemplate(FreemarkerUtils.java:44)
        at com.github.viclovsky.swagger.coverage.utils.FreemarkerUtils.processTemplate(FreemarkerUtils.java:57)
        at com.github.viclovsky.swagger.coverage.core.writer.HtmlReportResultsWriter.write(HtmlReportResultsWriter.java:43)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.lambda$run$3(Generator.java:53)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at com.github.viclovsky.swagger.coverage.core.generator.Generator.run(Generator.java:53)
        at com.github.viclovsky.swagger.coverage.CommandLine.run(CommandLine.java:74)
        at java.util.Optional.orElseGet(Optional.java:267)
        at com.github.viclovsky.swagger.coverage.CommandLine.main(CommandLine.java:35)
Exception in thread "main" java.lang.RuntimeException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> value.getParameters()  [in template "details/operation.ftl" at line 39, column 48]
```

In code https://github.com/viclovsky/swagger-coverage/blob/master/swagger-coverage-commons/src/main/resources/details/operation.ftl
```
 <tbody>
                                        <#list value.getParameters() as p>
                                            <tr>
                                                <td>${p.getName()}</td>
                                                <#if p.getExtensions()??>
                                                    <#if p.getExtensions()["x-example"]??>
                                                        <#if p.getExtensions()["x-example"]?is_boolean>
                                                            <td>${p.getExtensions()["x-example"]?c}</td>
                                                        <#else>
                                                            <td>${p.getExtensions()["x-example"]}</td>
                                                        </#if>
                                                    </#if>
                                                <#elseif p.getExample()??>
                                                    <#if p.getExample()?is_boolean>
                                                        <td>${p.getExample()?c}</td>
                                                    <#else>
                                                        <td>${p.getExample()}</td>
                                                    </#if>
                                                </#if>
                                            </tr>
                                        </#list>
                                    </tbody>
```

Example from spec
```
"paths": {
"/raise_test": {
      "get": {
        "summary": "Raise Test",
        "operationId": "raise_test_raise_test_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                }
              }
            }
          }
        }
      }
    }
}
```

#### What is the expected behavior?
Generate report from open-api.json spec without "parameters"

**Comment by viclovsky** [comment]
https://github.com/viclovsky/swagger-coverage/pull/89
